version: 3.0.2
services:
  key-server:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    entrypoint: ./bin/entrypoint
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:3005/ping || exit 1
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 20s
    develop:
      watch:
        - action: rebuild
          path: ./src
  redis:
    image: redis:7.4.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning

