name: Deploy Dev Webapp Build

on:
  push:
    branches: [ "main", "devel" ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag srs-key-control
  deploy-web-dev:
    environment: dev
    permissions:
      id-token: write
      pull-requests: write
      contents: read
    defaults:
      run:
        working-directory: './web/srs-key-control-panel'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy files
        run: mv ./dist/srs-key-control-panel/browser/* ./dist/srs-key-control-panel/
      
      - name: Delete old files
        run: az storage blob delete-batch --account-name ${{ vars.BLOB_ACCOUNT_NAME }} -s '$web' --pattern '*' --debug

      - name: Upload to blob storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
              az storage blob upload-batch --account-name ${{ vars.BLOB_ACCOUNT_NAME }} -d '$web' -s $GITHUB_WORKSPACE/dist/srs-key-control-panel/ --debug --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v2
        with:
          inlineScript: |
             az cdn endpoint purge --content-paths  "/*" --profile-name "${{ vars.CDN_PROFILE_NAME }}" --name "${{ vars.CDN_NAME }}" --resource-group "telepresence"

  
