name: Deploy Dev Webapp Build

on:
  push:
    branches: [ "main", "devel" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: offkai/ssc-api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: dev
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.REGISTRY }}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=inline
          
  deploy-web-dev:
    environment: dev
    permissions:
      id-token: write
      pull-requests: write
      contents: read
    defaults:
      run:
        working-directory: './web/srs-key-control-panel'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy files
        run: mv ./dist/srs-key-control-panel/browser/* ./dist/srs-key-control-panel/
      
      - name: Delete old files
        run: az storage blob delete-batch --account-name ${{ vars.BLOB_ACCOUNT_NAME }} -s '$web' --pattern '*' --debug

      - name: Upload to blob storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
              az storage blob upload-batch --account-name ${{ vars.BLOB_ACCOUNT_NAME }} -d '$web' -s $GITHUB_WORKSPACE/web/srs-key-control-panel/dist/srs-key-control-panel/ --debug --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v2
        with:
          inlineScript: |
             az cdn endpoint purge --content-paths  "/*" --profile-name "${{ vars.CDN_PROFILE_NAME }}" --name "${{ vars.CDN_NAME }}" --resource-group "telepresence"

  
