name: Docker Image & Webapp Build

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ ".github/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag srs-key-control
  build-webapp:
    defaults:
      run:
        working-directory: './web/srs-key-control-panel'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
