name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    defaults:
      run:
        working-directory: './web/srs-key-control-panel'
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/srs-key-control-panel s3://${{ secrets.SSC_DOMAIN_NAME }} --delete

